[package]
name = "invalidation_service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bloomfilter = "1.0.12"
actix-web = "4"
time = {version="0.3.30", features = ["local-offset", "formatting"]}
